language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

install:
  - python setup.py develop

script:
  - py.test tests --doctest-modules --pep8 geocoder -v --cov geocoder --cov-report term-missing

after_success:
  - coveralls

notifications:
  email:
    - carriere.denis@gmail.com
