language: python

python:
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
  - pip install -r requirements.txt && python setup.py develop

script:
  - py.test test_geocoder.py

notifications:
  email:
    - carriere.denis@gmail.com