site_name: Python Geocoder API
theme: readthedocs
Authors: Denis Carriere
Date: February 28, 2015
repo_url: https://github.com/DenisCarriere/geocoder
base_url: http://geocoder.readthedocs.org
markdown_extensions: ['tables', 'toc', 'meta', 'fenced_code']

pages:
- Home: index.md
- User Guide:
  - Install: Install.md
- Features:
  - GeoJSON: features/GeoJSON.md
  - Command Line Interface: features/Command Line Interface.md
  - Confidence Score: features/Confidence Score.md
  - Well-Known Text: features/Well-Known Text.md
  - Distance Tool: features/Distance.md
- Examples:
  - Write to CSV: examples/write to csv.md
  - Using iPython: examples/using iPython.md
  - Using Proxies: examples/using proxies.md
- Providers:
  - Google: providers/Google.md
  - Bing: providers/Bing.md
  - What3Words: providers/What3Words.md
  - OpenStreetMap: providers/OpenStreetMap.md
  - HERE: providers/HERE.md
  - OpenCage: providers/OpenCage.md
  - GeoOttawa: providers/GeoOttawa.md
  - CanadaPost: providers/CanadaPost.md
  - Geocoder.ca: providers/Geocoder-ca.md
  - GeoNames: providers/GeoNames.md
  - MapQuest: providers/MapQuest.md
  - ArcGIS: providers/ArcGIS.md
  - Baidu: providers/Baidu.md
  - Yandex: providers/Yandex.md
  - Yahoo: providers/Yahoo.md
  - TomTom: providers/TomTom.md
  - FreeGeoIP: providers/FreeGeoIP.md
  - MaxMind: providers/MaxMind.md
