site_name: geocoder
# docs_dir: './'
theme: readthedocs
# use_directory_urls: false
repo_url: https://github.com/DenisCarriere/geocoder
markdown_extensions: ['tables']
pages:
- ['index.md', 'Home']
- ['Quickstart.md', 'User Guide', 'Quickstart']
- ['Command Line Interface.md', 'Command Line Interface']
- ['providers/HERE.md', 'Providers', 'HERE']